var searchData=
[
  ['niveleducativoresponsedto_0',['NivelEducativoResponseDTO',['../classcom_1_1example_1_1sblprueba_1_1dto_1_1response_1_1_nivel_educativo_response_d_t_o.html',1,'com.example.sblprueba.dto.response.NivelEducativoResponseDTO'],['../classcom_1_1example_1_1sblprueba_1_1dto_1_1response_1_1_nivel_educativo_response_d_t_o.html#a0e9f025c4451c841805ad002938d76bd',1,'com.example.sblprueba.dto.response.NivelEducativoResponseDTO.NivelEducativoResponseDTO(Long idNivelEducativo, String descripcion)'],['../classcom_1_1example_1_1sblprueba_1_1dto_1_1response_1_1_nivel_educativo_response_d_t_o.html#a3a4c340fb3c3324bd1d9b3ce7d14a4fe',1,'com.example.sblprueba.dto.response.NivelEducativoResponseDTO.NivelEducativoResponseDTO(SblNivelesEducativosEntity s)']]],
  ['niveleducativoresponsedto_2ejava_1',['NivelEducativoResponseDTO.java',['../_nivel_educativo_response_d_t_o_8java.html',1,'']]],
  ['niveleseducativosrepository_2',['NivelesEducativosRepository',['../interfacecom_1_1example_1_1sblprueba_1_1repository_1_1_niveles_educativos_repository.html',1,'com::example::sblprueba::repository']]],
  ['niveleseducativosrepository_2ejava_3',['NivelesEducativosRepository.java',['../_niveles_educativos_repository_8java.html',1,'']]],
  ['niveleseducativosrequestdto_4',['NivelesEducativosRequestDTO',['../classcom_1_1example_1_1sblprueba_1_1dto_1_1request_1_1_niveles_educativos_request_d_t_o.html',1,'com.example.sblprueba.dto.request.NivelesEducativosRequestDTO'],['../classcom_1_1example_1_1sblprueba_1_1dto_1_1request_1_1_niveles_educativos_request_d_t_o.html#a90e3a7acaef82af9b2f0aa775cd3d2fe',1,'com.example.sblprueba.dto.request.NivelesEducativosRequestDTO.NivelesEducativosRequestDTO()'],['../classcom_1_1example_1_1sblprueba_1_1dto_1_1request_1_1_niveles_educativos_request_d_t_o.html#a180d5b10c1a71cbca52470739c6c2247',1,'com.example.sblprueba.dto.request.NivelesEducativosRequestDTO.NivelesEducativosRequestDTO(Long idniveleducativo, String descripcion)'],['../classcom_1_1example_1_1sblprueba_1_1dto_1_1request_1_1_niveles_educativos_request_d_t_o.html#a4f1cf94aa8eece5320d4e8ba504d6b4c',1,'com.example.sblprueba.dto.request.NivelesEducativosRequestDTO.NivelesEducativosRequestDTO(SblNivelesEducativosEntity item)']]],
  ['niveleseducativosrequestdto_2ejava_5',['NivelesEducativosRequestDTO.java',['../_niveles_educativos_request_d_t_o_8java.html',1,'']]],
  ['niveleseducativosservice_6',['NivelesEducativosService',['../classcom_1_1example_1_1sblprueba_1_1service_1_1_niveles_educativos_service.html',1,'com::example::sblprueba::service']]],
  ['niveleseducativosservice_2ejava_7',['NivelesEducativosService.java',['../_niveles_educativos_service_8java.html',1,'']]],
  ['notfoundentity_8',['NotFoundEntity',['../classcom_1_1example_1_1sblprueba_1_1exceptions_1_1_not_found_entity.html',1,'com.example.sblprueba.exceptions.NotFoundEntity'],['../classcom_1_1example_1_1sblprueba_1_1exceptions_1_1_not_found_entity.html#ae92625012ac38d2c5aebed0a9cb76969',1,'com.example.sblprueba.exceptions.NotFoundEntity.NotFoundEntity(String entity, Long id)'],['../classcom_1_1example_1_1sblprueba_1_1exceptions_1_1_not_found_entity.html#a5ed9e25c0abcac19906bc828b4e34c27',1,'com.example.sblprueba.exceptions.NotFoundEntity.NotFoundEntity(String message)'],['../classcom_1_1example_1_1sblprueba_1_1exceptions_1_1_not_found_entity.html#ab8d81102c8f24811e00899942dcb7260',1,'com.example.sblprueba.exceptions.NotFoundEntity.NotFoundEntity(String message, String message1)'],['../classcom_1_1example_1_1sblprueba_1_1exceptions_1_1_not_found_entity.html#ac58a68b97845914dc3efab87c002487a',1,'com.example.sblprueba.exceptions.NotFoundEntity.NotFoundEntity(String message, Throwable cause, String message1)'],['../classcom_1_1example_1_1sblprueba_1_1exceptions_1_1_not_found_entity.html#a066ec57e5a8f47a1642d97278ffc2bad',1,'com.example.sblprueba.exceptions.NotFoundEntity.NotFoundEntity(Throwable cause, String message)'],['../classcom_1_1example_1_1sblprueba_1_1exceptions_1_1_not_found_entity.html#a4240fce7da16df0e3dfee8d70998754c',1,'com.example.sblprueba.exceptions.NotFoundEntity.NotFoundEntity(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, String message1)']]],
  ['notfoundentity_2ejava_9',['NotFoundEntity.java',['../_not_found_entity_8java.html',1,'']]]
];
